
Lmod is automatically replacing "intel/2020.1.217" with "gcc/9.3.0".


Due to MODULEPATH changes, the following have been reloaded:
  1) libfabric/1.10.1     2) openmpi/4.0.3     3) ucx/1.8.0

Using 1 GPU for training... 
training args are: Namespace(batch_size=32, bs_per_gpu=32, calib=False, check_images=False, check_labels=False, conf_file='configs/yolov6l6_finetune.py', data_path='datasets/metatrain/neu_det.yaml', device='0', dist_url='env://', distill=False, distill_feat=False, epochs=100, eval_final_only=False, eval_interval=20, fuse_ab=False, gpu_count=0, heavy_eval_range=50, img_size=320, local_rank=-1, name='train_6l6-32-320', output_dir='results', quant=False, rank=-1, resume=False, save_ckpt_on_last_n_epoch=-1, save_dir='results/train_6l6-32-3209', stop_aug_last_n_epoch=15, teacher_model_path=None, temperature=20, workers=8, world_size=1, write_trainbatch_tb=False)

Traceback (most recent call last):
  File "tools/train.py", line 128, in <module>
    main(args)
  File "tools/train.py", line 113, in main
    trainer = Trainer(args, cfg, device)
  File "/gpfs/scratch/rayen/NEU_DET_YOLOV63/yolov6/core/engine.py", line 52, in __init__
    self.data_dict = load_yaml(args.data_path)
  File "/gpfs/scratch/rayen/NEU_DET_YOLOV63/yolov6/utils/events.py", line 22, in load_yaml
    with open(file_path, errors='ignore') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/metatrain/neu_det.yaml'
